---
Name: analyticsrequestprocessor
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        CustomMiddleware: '%$WakeWorks\Analytics\Middlewares\AnalyticsProcessorMiddleware'

SilverStripe\Control\Controller:
  extensions:
    - WakeWorks\Analytics\Extensions\ControllerExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'wakeworks/analytics:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'wakeworks/analytics:client/dist/styles/bundle.css'
